 spring.application.name=quesadvisor
server.port=8081

logging.level.org.springframework.ai.chat.client.advisor=DEBUG

spring.datasource.url=jdbc:mariadb://localhost:3308/spring_ai
spring.datasource.username=root
spring.datasource.password=root

spring.ai.ollama.base-url=http://localhost:11434

# Chat model
spring.ai.ollama.chat.options.model=codellama

# Embedding model (IMPORTANT)
spring.ai.ollama.embedding.options.model=nomic-embed-text

spring.ai.vectorstore.mariadb.initialize-schema=true
spring.ai.vectorstore.mariadb.distance-type=COSINE
spring.ai.vectorstore.mariadb.dimensions=768