spring.application.name=jdbc-repo
server.port=8081

logging.level.org.springframework.ai.chat.client.advisor=DEBUG

spring.datasource.url=jdbc:postgresql://localhost:5432/ai_chat_memory
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

logging.level.org.springframework.jdbc=DEBUG

spring.ai.chat.memory.repository.jdbc.initialize-schema=ALWAYS


